import { type NextPage } from "next";
import Head from "next/head";
import Layout from "components/Layout";
import PostInitiator from "components/PostInitiator";
import Posts from "components/Posts";
import React from "react";
import TopCommunities from "components/TopCommunities";

const Home: NextPage = () => {
  const layoutLeftComponent: React.FC = () => {
    return (
      <>
        <PostInitiator />
        <Posts />
      </>
    );
  };

  const layoutRightComponent: React.FC = () => {
    return (
      <>
        <TopCommunities />
      </>
    );
  };

  return (
    <>
      <Head>
        <title>Main Page</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout Left={layoutLeftComponent} Right={layoutRightComponent} />
    </>
  );
};

export default Home;
