import { type NextPage } from "next";
import Head from "next/head";
import Layout from "components/Layout";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Main Page</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout />
    </>
  );
};

export default Home;
